/* =========================================================
   数据层：项目内容 + 中英德三语界面文案
   所有图片均为占位图（assets/img/*.svg），后续替换为真实作品即可。
   ========================================================= */

/* ---------- 界面文案 (i18n) ---------- */
const I18N = {
  zh: {
    dir: "ltr",
    nav_works: "作品",
    nav_about: "关于",
    nav_contact: "联系",
    hero_kicker: "摄影 · 视觉艺术",
    hero_title: "尤浈棋",
    hero_sub: "在光与静默之间，记录未被言说的瞬间。",
    hero_scroll: "向下滚动",
    works_title: "作品合集",
    works_sub: "六个长期项目，一组关于时间、空间与凝视的私人档案。",
    detail_back: "返回作品",
    detail_about: "项目自述",
    detail_caption: "图注",
    detail_next: "下一项目",
    about_title: "关于艺术家",
    about_text: "尤浈棋，影像创作者，长期游走于纪实与诗性之间。作品关注被忽略的边缘风景、城市切片与物之静默，试图在快门之间留住时间的褶皱。这里展示的是阶段性归档，全部图片均为占位示意，正式作品将陆续替换。",
    about_text2: "展历与收藏信息敬请期待。",
    contact_title: "联系",
    contact_text: "展览合作、作品收藏与委约拍摄，欢迎来信。",
    contact_email: "邮箱",
    contact_studio: "工作室",
    lang_label: "语言",
    theme_light: "白天",
    theme_dark: "黑夜",
    footer: "© 2026 尤浈棋 · 版权所有 · 占位演示站点",
  },
  en: {
    dir: "ltr",
    nav_works: "Works",
    nav_about: "About",
    nav_contact: "Contact",
    hero_kicker: "Photography · Visual Art",
    hero_title: "Yóu Zhēnqí",
    hero_sub: "Between light and silence, recording the unspoken moment.",
    hero_scroll: "Scroll down",
    works_title: "Selected Works",
    works_sub: "Six long-term projects — a private archive of time, space and the gaze.",
    detail_back: "Back to works",
    detail_about: "Statement",
    detail_caption: "Caption",
    detail_next: "Next project",
    about_title: "About the Artist",
    about_text: "Yóu Zhēnqí is an image-maker drifting between documentary and the poetic. The work attends to overlooked edge landscapes, urban slices and the silence of things, trying to keep the folds of time within the shutter. This is a staged archive; all images are placeholders to be replaced by final works.",
    about_text2: "Exhibition history and collections coming soon.",
    contact_title: "Contact",
    contact_text: "For exhibitions, acquisitions and commissions, please write.",
    contact_email: "Email",
    contact_studio: "Studio",
    lang_label: "Language",
    theme_light: "Light",
    theme_dark: "Dark",
    footer: "© 2026 Yóu Zhēnqí · All rights reserved · Placeholder demo site",
  },
  de: {
    dir: "ltr",
    nav_works: "Werke",
    nav_about: "Über",
    nav_contact: "Kontakt",
    hero_kicker: "Fotografie · Visuelle Kunst",
    hero_title: "Yóu Zhēnqí",
    hero_sub: "Zwischen Licht und Stille das Ungesagte festhalten.",
    hero_scroll: "Nach unten scrollen",
    works_title: "Ausgewählte Werke",
    works_sub: "Sechs Langzeitprojekte — ein privates Archiv aus Zeit, Raum und Blick.",
    detail_back: "Zurück zu Werken",
    detail_about: "Statement",
    detail_caption: "Bildunterschrift",
    detail_next: "Nächstes Projekt",
    about_title: "Über die Künstlerin",
    about_text: "Yóu Zhēnqí ist Bildgestalterin zwischen Dokumentarischem und Poetischem. Die Arbeit widmet sich übersehenen Randlandschaften, Stadtschnitten und dem Schweigen der Dinge und sucht, die Falten der Zeit im Verschluss zu bewahren. Dies ist ein Zwischenarchiv; alle Bilder sind Platzhalter und werden durch Endfassungen ersetzt.",
    about_text2: "Ausstellungen und Sammlungen folgen.",
    contact_title: "Kontakt",
    contact_text: "Für Ausstellungen, Ankäufe und Aufträge schreiben Sie gern.",
    contact_email: "E-Mail",
    contact_studio: "Atelier",
    lang_label: "Sprache",
    theme_light: "Tag",
    theme_dark: "Nacht",
    footer: "© 2026 Yóu Zhēnqí · Alle Rechte vorbehalten · Platzhalter-Demo",
  },
};

/* ---------- 项目数据 ---------- */
/* intro / about 三语；gallery 为占位图路径；meta 为年份/媒介 */
const PROJECTS = [
  {
    id: "p1",
    cover: "assets/img/p1-cover.svg",
    year: "2023",
    medium: { zh: "艺术微喷 · 收藏级", en: "Archival pigment print", de: "Archiv- Pigmentdruck" },
    title: { zh: "雾屿", en: "Misty Isles", de: "Nebelinseln" },
    intro: {
      zh: "在海雾反复擦去地平线的日子里，岛屿成为悬浮的句读。这组作品记录潮间带被光线缓慢涂抹的过程，以及人迹退场后留下的空。",
      en: "On days when sea fog repeatedly erases the horizon, the islands become suspended punctuation. The series records how the tideline is slowly painted by light, and the emptiness left after people retreat.",
      de: "An Tagen, da Nebel den Horizont löscht, werden Inseln zu schwebender Interpunktion. Die Serie zeigt, wie das Licht die Ufer langsam malt und was bleibt, wenn die Menschen gehen.",
    },
    about: {
      zh: "《雾屿》始于一次漫长的海岸停留。我用长曝光让浪与雾彼此溶解，试图拍下'几乎什么都没有发生'的那一刻——那是风景最诚实的状态。",
      en: "Misty Isles began with a long stay on the coast. Long exposures let waves and fog dissolve into each other; I wanted the moment when almost nothing happens — the most honest state of a landscape.",
      de: "Nebelinseln begann mit einem langen Aufenthalt an der Küste. Langzeitbelichtung lässt Wellen und Nebel eins werden; ich suchte den Moment, in dem fast nichts geschieht — der ehrlichste Zustand einer Landschaft.",
    },
    gallery: [
      { src: "assets/img/p1-1.svg", caption: { zh: "退潮，07:12", en: "Ebb, 07:12", de: "Ebbe, 07:12" } },
      { src: "assets/img/p1-2.svg", caption: { zh: "悬浮的礁", en: "Floating reef", de: "Schwebendes Riff" } },
      { src: "assets/img/p1-3.svg", caption: { zh: "雾中轮廓", en: "Outline in mist", de: "Umriss im Nebel" } },
      { src: "assets/img/p1-4.svg", caption: { zh: "盐与风", en: "Salt and wind", de: "Salz und Wind" } },
      { src: "assets/img/p1-5.svg", caption: { zh: "无人的岸", en: "Empty shore", de: "Leerer Strand" } },
      { src: "assets/img/p1-6.svg", caption: { zh: "归航之前", en: "Before return", de: "Vor der Rückkehr" } },
    ],
  },
  {
    id: "p2",
    cover: "assets/img/p2-cover.svg",
    year: "2022",
    medium: { zh: "银盐 · 手工放大", en: "Silver gelatin print", de: "Silbergelatine" },
    title: { zh: "城市切片", en: "Urban Slices", de: "Stadtschnitte" },
    intro: {
      zh: "把城市竖切成片，每一片都是一种速度。玻璃、混凝土与人群在快门里被压平成图案，城市的呼吸因此可见。",
      en: "Slicing the city vertically, each slice is a kind of speed. Glass, concrete and crowds are flattened into pattern; the city's breathing becomes visible.",
      de: "Die Stadt vertikal geschnitten — jeder Schnitt eine Geschwindigkeit. Glas, Beton und Menschen werden zur Fläche; das Atmen der Stadt wird sichtbar.",
    },
    about: {
      zh: "《城市切片》用仰拍与镜面反射拆解熟悉的街景。我想追问：当我们抬头，城市是否换了一副面孔？",
      en: "Urban Slices deconstructs familiar streets with upward angles and mirror reflections. I ask: when we look up, does the city wear another face?",
      de: "Stadtschnitte bricht vertraute Straßen durch Aufsichten und Spiegelungen auf. Die Frage: trägt die Stadt ein anderes Gesicht, wenn wir aufsehen?",
    },
    gallery: [
      { src: "assets/img/p2-1.svg", caption: { zh: "正午反光", en: "Noon glare", de: "Mittagsreflex" } },
      { src: "assets/img/p2-2.svg", caption: { zh: "电梯井", en: "Elevator shaft", de: "Aufzugschacht" } },
      { src: "assets/img/p2-3.svg", caption: { zh: "人潮", en: "Crowd", de: "Menschenstrom" } },
      { src: "assets/img/p2-4.svg", caption: { zh: "脚手架", en: "Scaffold", de: "Gerüst" } },
      { src: "assets/img/p2-5.svg", caption: { zh: "霓虹残影", en: "Neon ghost", de: "Neonrest" } },
      { src: "assets/img/p2-6.svg", caption: { zh: "夜的边界", en: "Edge of night", de: "Rand der Nacht" } },
    ],
  },
  {
    id: "p3",
    cover: "assets/img/p3-cover.svg",
    year: "2024",
    medium: { zh: "艺术微喷 · 收藏级", en: "Archival pigment print", de: "Archiv- Pigmentdruck" },
    title: { zh: "静物之间", en: "Between Still Lifes", de: "Zwischen Stilleben" },
    intro: {
      zh: "物在等待被注视时才成为静物。这组近摄记录桌面上光线的短暂停留——一杯水、一片叶、一段被遗忘的时间。",
      en: "Things become still lifes only when waited upon by a gaze. Close-ups record light's brief stay on a table — a glass of water, a leaf, a forgotten stretch of time.",
      de: "Dinge werden zum Stilleben erst im erwartenden Blick. Nahaufnahmen halten das kurze Verweilen des Lichts fest — ein Wasserglas, ein Blatt, vergessene Zeit.",
    },
    about: {
      zh: "《静物之间》是一次关于'慢'的练习。我把日常之物从用途里解放出来，让它们仅仅作为光与影存在。",
      en: "Between Still Lifes is an exercise in slowness. I free everyday objects from use, letting them exist merely as light and shadow.",
      de: "Zwischen Stilleben ist eine Übung im Langsamsein. Ich befreie Dinge vom Gebrauch und lasse sie nur als Licht und Schatten sein.",
    },
    gallery: [
      { src: "assets/img/p3-1.svg", caption: { zh: "一杯水", en: "A glass of water", de: "Ein Wasserglas" } },
      { src: "assets/img/p3-2.svg", caption: { zh: "枯叶", en: "Dry leaf", de: "Trockenes Blatt" } },
      { src: "assets/img/p3-3.svg", caption: { zh: "布纹", en: "Cloth", de: "Stoff" } },
      { src: "assets/img/p3-4.svg", caption: { zh: "窗台", en: "Windowsill", de: "Fensterbrett" } },
      { src: "assets/img/p3-5.svg", caption: { zh: "影与器", en: "Shadow and vessel", de: "Schatten und Gefäß" } },
      { src: "assets/img/p3-6.svg", caption: { zh: "余温", en: "Residual warmth", de: "Verbleibende Wärme" } },
    ],
  },
  {
    id: "p4",
    cover: "assets/img/p4-cover.svg",
    year: "2021",
    medium: { zh: "灯箱片 · 背光", en: "Backlit transparency", de: "Leuchtkasten" },
    title: { zh: "光的褶皱", en: "Folds of Light", de: "Falten des Lichts" },
    intro: {
      zh: "光不是均匀的。它折叠、堆积、在某处忽然明亮。这组作品用逆光捕捉织物的呼吸，以及光自己写下的形状。",
      en: "Light is not even. It folds, piles up, brightens suddenly somewhere. Shot against the light, the series catches the breath of cloth and the shapes light writes itself.",
      de: "Licht ist nicht gleichmäßig. Es faltet, türmt sich, wird plötzlich hell. Gegen das Licht gefilmt, fängt die Serie den Atem des Stoffs und die Formen, die Licht selbst schreibt.",
    },
    about: {
      zh: "《光的褶皱》把丝绸与晨光并置。我想拍的从来不是布，而是光经过它时发生的犹豫。",
      en: "Folds of Light places silk beside morning light. I never meant to photograph cloth, but the hesitation light shows passing through it.",
      de: "Falten des Lichts stellt Seide neben Morgenlicht. Gemeint war nie der Stoff, sondern das Zögern des Lichts auf dem Weg hindurch.",
    },
    gallery: [
      { src: "assets/img/p4-1.svg", caption: { zh: "晨光", en: "Morning light", de: "Morgenlicht" } },
      { src: "assets/img/p4-2.svg", caption: { zh: "丝绸", en: "Silk", de: "Seide" } },
      { src: "assets/img/p4-3.svg", caption: { zh: "折角", en: "Fold", de: "Falte" } },
      { src: "assets/img/p4-4.svg", caption: { zh: "逆光", en: "Backlight", de: "Gegenlicht" } },
      { src: "assets/img/p4-5.svg", caption: { zh: "透", en: "Through", de: "Durch" } },
      { src: "assets/img/p4-6.svg", caption: { zh: "落幕", en: "Curtain", de: "Vorhang" } },
    ],
  },
  {
    id: "p5",
    cover: "assets/img/p5-cover.svg",
    year: "2023",
    medium: { zh: "艺术微喷 · 收藏级", en: "Archival pigment print", de: "Archiv- Pigmentdruck" },
    title: { zh: "边境漫游", en: "Border Drift", de: "Grenzwanderung" },
    intro: {
      zh: "沿着一条并不存在的线行走。荒原、界碑与无名的路，构成一组关于'之间'的影像——不属于这边，也不属于那边。",
      en: "Walking a line that does not exist. Wasteland, markers and nameless roads form images of 'in-between' — belonging neither here nor there.",
      de: "Entlang einer Linie, die nicht existiert. Ödland, Grenzsteine und namenlose Wege ergeben Bilder des 'Dazwischen' — weder hier noch dort.",
    },
    about: {
      zh: "《边境漫游》是一次徒步式的拍摄。我不寻找边界，而是寻找边界溶解的地方。",
      en: "Border Drift is a walking shoot. I did not seek the border, but where it dissolves.",
      de: "Grenzwanderung ist eine Wanderung mit der Kamera. Nicht die Grenze suchte ich, sondern wo sie sich auflöst.",
    },
    gallery: [
      { src: "assets/img/p5-1.svg", caption: { zh: "界碑", en: "Marker", de: "Grenzstein" } },
      { src: "assets/img/p5-2.svg", caption: { zh: "无名路", en: "Nameless road", de: "Namenloser Weg" } },
      { src: "assets/img/p5-3.svg", caption: { zh: "荒原", en: "Wasteland", de: "Ödland" } },
      { src: "assets/img/p5-4.svg", caption: { zh: "远山", en: "Distant hills", de: "Ferne Hügel" } },
      { src: "assets/img/p5-5.svg", caption: { zh: "风的方向", en: "Wind's direction", de: "Windrichtung" } },
      { src: "assets/img/p5-6.svg", caption: { zh: "黄昏线", en: "Dusk line", de: "Dämmerungslinie" } },
    ],
  },
  {
    id: "p6",
    cover: "assets/img/p6-cover.svg",
    year: "2024",
    medium: { zh: "艺术微喷 · 收藏级", en: "Archival pigment print", de: "Archiv- Pigmentdruck" },
    title: { zh: "无人之境", en: "No Man's Land", de: "Niemandsland" },
    intro: {
      zh: "在被遗忘的房间里，时间以另一种速度流动。这组作品凝视空置空间里的痕迹——它们比人更长久地记得发生过什么。",
      en: "In forgotten rooms, time flows at another speed. The series gazes at traces in vacant spaces — they remember longer than people what happened.",
      de: "In vergessenen Räumen fließt die Zeit anders. Die Serie blickt auf Spuren in leeren Räumen — sie erinnern länger als Menschen, was geschah.",
    },
    about: {
      zh: "《无人之境》拍摄废弃居所。我让相机替离开的人，再看一眼他们留下的安静。",
      en: "No Man's Land photographs abandoned homes. The camera looks once more, for those who left, at the quiet they left behind.",
      de: "Niemandsland fotografiert verlassene Wohnungen. Die Kamera blickt ein letztes Mal für die Gegangenen auf ihre Stille.",
    },
    gallery: [
      { src: "assets/img/p6-1.svg", caption: { zh: "空椅", en: "Empty chair", de: "Leerer Stuhl" } },
      { src: "assets/img/p6-2.svg", caption: { zh: "剥落的墙", en: "Peeling wall", de: "Bröckelnde Wand" } },
      { src: "assets/img/p6-3.svg", caption: { zh: "窗与尘", en: "Window and dust", de: "Fenster und Staub" } },
      { src: "assets/img/p6-4.svg", caption: { zh: "遗物", en: "Remains", de: "Hinterlassenschaft" } },
      { src: "assets/img/p6-5.svg", caption: { zh: "走廊尽头", en: "End of corridor", de: "Flurende" } },
      { src: "assets/img/p6-6.svg", caption: { zh: "最后的房间", en: "Last room", de: "Letzter Raum" } },
    ],
  },
];

window.__SITE_DATA__ = { I18N, PROJECTS };
